txt <- readLines('monitora_campsav_alvo_global_v2.6.0.R', warn=FALSE)
i <- grep('^# ---- contrato único consolidado 2026-07-07 ----$', txt); j <- grep('^# ---- fim contrato único consolidado 2026-07-07 ----$', txt)
stopifnot(length(i)==1, length(j)==1, j>i)
eval(parse(text=paste(txt[i:j], collapse='\n')), envir=.GlobalEnv)
stopifnot(isTRUE(monitora_cu_20260707()$perfil_painel_edicao$autoridade))
ch <- monitora_cu_choice_20260707('Label amigável','token_tecnico'); stopifnot(unname(ch)=='token_tecnico', grepl('Label amigável', names(ch)), grepl('token_tecnico', names(ch)))
stopifnot(isTRUE(monitora_cu_forma_valida_20260707('Outras plantas terrestres, líquens e/ou fungos')))
stopifnot(isTRUE(monitora_cu_legado_outra_forma_vida_20260707('outra_forma_vida')))
stopifnot(!isTRUE(monitora_cu_legado_outra_forma_vida_20260707('Outras plantas terrestres, líquens e/ou fungos')))
idx <- data.frame(tipo_ocorrencia=c('nativa_sem_forma_vida','pipe_residual_estruturado'), stringsAsFactors=FALSE)
idx2 <- monitora_cu_normalizar_ocorr_20260707(idx); stopifnot(all(monitora_cu_ocorr_campos_20260707() %in% names(idx2)))
stopifnot(nrow(monitora_cu_resumo_ocorr_20260707(idx2))==2)
stopifnot(isTRUE(monitora_cu_export_ok_20260707('S', FALSE)), !isTRUE(monitora_cu_export_ok_20260707('S', TRUE)), identical(monitora_cu_tokens_20260707('a|b|a'), c('a','b')))
cat('SYNTHETIC_TESTS_OK\n')
