args<-commandArgs(TRUE);root<-normalizePath(args[1]);files<-list.files(root,pattern=if(length(args)>1L)args[2]else'^analitico_.*[.]html$',recursive=TRUE,full.names=TRUE)
stopifnot(length(files)>=1);result<-list()
for(p in files){
 d<-xml2::read_html(p);norm<-function(x)trimws(gsub('[[:space:]]+',' ',x));expected<-lapply(xml2::xml_find_all(d,'.//table'),function(t)list(id=xml2::xml_attr(t,'aria-labelledby'),caption=norm(xml2::xml_text(xml2::xml_find_first(d,paste0(".//*[@id='",xml2::xml_attr(t,'aria-labelledby'),"']")))),rows=as.list(norm(xml2::xml_text(xml2::xml_find_all(t,'./tbody/tr'))))))
 s<-chromote::ChromoteSession$new();s$Page$navigate(paste0('file://',p));s$Page$loadEventFired()
 s$Runtime$evaluate("new Promise(resolve=>{let prev=-1,stable=0,n=0;let t=setInterval(()=>{n++;let count=document.querySelectorAll('.pagedjs_page').length;if(count>0&&count===prev)stable++;else stable=0;prev=count;if(stable>8||n>180){clearInterval(t);resolve(count)}},500)})",awaitPromise=TRUE)
 js<-paste0("JSON.stringify((()=>{let expected=",jsonlite::toJSON(expected,auto_unbox=TRUE),";let all=[...document.querySelectorAll('.pagedjs_page table')];let norm=x=>x.replace(/\\s+/g,' ').trim();return{captionErrors:expected.flatMap(t=>{let caps=[...document.querySelectorAll('.pagedjs_page .monitora-legenda-tabela')].filter(p=>p.id===t.id);let tab=all.find(x=>x.getAttribute('aria-labelledby')===t.id&&x.querySelector('tbody tr td')); return caps.length===1&&norm(caps[0].textContent)===t.caption&&tab&&caps[0].closest('.pagedjs_page')===tab.closest('.pagedjs_page')?[]:[t.id]}),pages:document.querySelectorAll('.pagedjs_page').length,numericErrors:[...document.querySelectorAll('.pagedjs_page td,.pagedjs_page th')].filter(t=>t.scrollWidth>t.clientWidth+1).map(t=>({texto:t.textContent,largura:t.clientWidth,conteudo:t.scrollWidth})),layout:all.map(t=>{let p=t.closest('.pagedjs_page'),a=p.querySelector('.pagedjs_area'),b=a.getBoundingClientRect(),cs=[...t.querySelectorAll('th:not([data-monitora-clipped]),td:not([data-monitora-clipped])')].map(c=>c.getBoundingClientRect()),r={right:Math.max(...cs.map(c=>c.right)),left:Math.min(...cs.map(c=>c.left))};return{page:p.dataset.pageNumber,id:t.getAttribute('aria-labelledby'),headers:t.querySelectorAll('thead tr').length,right:r.right-b.right,left:b.left-r.left}}).filter(x=>x.headers>1||x.right>2||x.left>2),missing:expected.flatMap(t=>{let got=all.filter(x=>x.getAttribute('aria-labelledby')===t.id).flatMap(x=>[...x.querySelectorAll('tbody tr')].filter(r=>r.querySelector('td:not([data-monitora-clipped])')).map(r=>norm(r.textContent)));return t.rows.filter(r=>r&&!got.includes(r)).map(r=>({id:t.id,row:r}))})}})())")
 z<-jsonlite::fromJSON(s$Runtime$evaluate(js,returnByValue=TRUE)$result$value,simplifyVector=FALSE)
 s$Emulation$setEmulatedMedia(media='print')
 manifest<-"JSON.stringify([...document.querySelectorAll('.pagedjs_page')].map(p=>{let b=p.querySelector('.pagedjs_pagebox').getBoundingClientRect(),s=p.querySelector('.pagedjs_sheet').getBoundingClientRect();return{numero:Number(p.dataset.pageNumber),largura:b.width*.75,altura:b.height*.75,folha_largura:s.width*.75,folha_altura:s.height*.75,celulas:[...p.querySelectorAll('th:not([data-monitora-clipped]),td:not([data-monitora-clipped])')].map(t=>t.textContent.replace(/\\s+/g,' ').trim())}}))"
 z$folhas<-jsonlite::fromJSON(s$Runtime$evaluate(manifest,returnByValue=TRUE)$result$value,simplifyVector=FALSE)
 stopifnot(all(vapply(z$folhas,function(p)abs(p$largura-p$folha_largura)<1 && p$largura<p$altura,logical(1))))
 jsfig<-"JSON.stringify([...document.querySelectorAll('.pagedjs_page figure')].map(f=>{let p=f.closest('.pagedjs_page'),a=p.querySelector('.pagedjs_area').getBoundingClientRect(),r=f.getBoundingClientRect();return{pagina:Number(p.dataset.pageNumber),texto:f.querySelector('figcaption')?.textContent,topo:r.top-a.top,fundo:a.bottom-r.bottom,largura:r.width,altura:r.height}}))"
 z$figuras<-jsonlite::fromJSON(s$Runtime$evaluate(jsfig,returnByValue=TRUE)$result$value,simplifyVector=FALSE)
 stopifnot(all(vapply(z$figuras,function(f)!is.null(f$texto)&&f$topo>= -2 && f$fundo>= -2,logical(1))))
 s$close();z$arquivo<-basename(p);result[[basename(p)]]<-z
}
jsonlite::write_json(result,file.path(root,'AUDITORIA_PAGINACAO.json'),auto_unbox=TRUE,pretty=TRUE)
stopifnot(all(vapply(result,function(x)length(x$captionErrors)==0 && length(x$layout)==0 && length(x$missing)==0 && length(x$numericErrors)==0,logical(1L))))
cat('PASS: tabelas paginadas sem extrapolar margens, sem cabeçalhos duplicados e com todas as linhas preservadas.\n')
