suppressPackageStartupMessages(library(data.table));source('tools/v305/carregar.R');e<-monitora_v305_carregar()
dir<-tempdir();stopifnot(e$monitora_v305_motivos(c('a; b','a','b; c'))=='a; b; c')
x<-c('# Resumo executivo','<div class="callout">Primeiro.<br><br>Segundo.</div>','# Métodos',e$monitora_relatorios_analiticos_kable(data.frame(Ano=2026,Formacao='Campestre',VIF=2),id='clima-diagnosticos'),'# Referências','BACI não deve consumir primeira ocorrência.')
y<-e$monitora_v305_editorial(x,dir,'teste');stopifnot(any(grepl('fator de inflação da variância [(]VIF[)]',y)),any(grepl('Glossário',y)),!any(grepl('desenho antes',y)))
w<-e$monitora_relatorios_analiticos_conteudo_docx(x);stopifnot(any(grepl('Primeiro.\n\nSegundo.',w,fixed=TRUE)))
a<-e$monitora_v305_larguras(c('Ano','Formação','Módulo'),matrix(c('2026','Campestre','Multivariada'),nrow=1));stopifnot(sum(a$larguras)==a$total,all(a$larguras>=a$minimos),!a$paisagem)
a<-e$monitora_v305_larguras(paste('Coluna',1:9),matrix(rep('3.14',9),nrow=1));stopifnot(!a$paisagem,sum(a$larguras)==a$total)
cat('PASS: módulo incorporado, motivos, primeira ocorrência, bibliografia, parágrafos e larguras.\n')
z<-data.frame(form_veg=c('campestre','campestre'),indicador_rotulo=c('Nativas','Material'),motivo=c('28 dias','29 dias'))
stopifnot(grepl('Nativas: 28 dias',e$monitora_v305_calendario(z),fixed=TRUE),grepl('Material: 29 dias',e$monitora_v305_calendario(z),fixed=TRUE))
x<-c('# Resumo',e$monitora_relatorios_analiticos_kable(data.frame(Indicador='Exóticas',`FDR-BH`=.1,check.names=FALSE),id='estado-prioritario'),'# Referências')
y<-e$monitora_v305_editorial(x,dir,'casos');a<-fread(file.path(dir,'siglas_casos.csv'))
stopifnot('FDR-BH'%in%a$sigla,!any(c('FDR','BH')%in%a$sigla),any(grepl('não demonstra invasão',y,fixed=TRUE)))
n<-e$monitora_relatorios_analiticos_numerar(y,dir);stopifnot(any(n$auditoria$id=='estado-prioritario'))
library(xml2)
d<-read_xml('<w:body xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:sectPr><w:pgMar/><w:pgSz w:w="11906"/><w:type/><w:pgSz w:w="16838"/></w:sectPr></w:body>')
for(i in 1:3){e$monitora_v305_ordenar_ooxml(d);gc()}
ns<-xml_ns(d);stopifnot(length(xml_find_all(d,'.//w:pgSz',ns))==1,xml_attr(xml_find_first(d,'.//w:pgSz',ns),'w')=='16838',identical(xml_name(xml_children(xml_find_first(d,'.//w:sectPr',ns))),c('type','pgSz','pgMar')))
cat('PASS: contexto por indicador, ressalva no sintético, sigla composta e OOXML com namespaces/ordem/unicidade.\n')

x<-c('# Resumo','<figure><img src="figuras/evidencia_estatistica_teste.png"><figcaption>Painel.</figcaption></figure>','# Referências')
y<-e$monitora_v305_editorial(x,dir,'graficos');a<-fread(file.path(dir,'siglas_graficos.csv'))
stopifnot(all(c('LB','AUM','RED','EST','INC','PAR','MUD','EST-C','H')%in%a$sigla),which(grepl('distância de Hellinger',y))[1]<which(startsWith(y,'<figure')))
cat('PASS: abreviações dos painéis raster inventariadas e definidas antes da primeira figura.\n')
