suppressPackageStartupMessages(library(data.table));source('tools/v305/carregar.R');e<-monitora_v305_carregar()
dir<-tempfile('retr_');dir.create(dir);dir.create(file.path(dir,'figuras'))
x<-CJ(Formação=c('Campestre','Savânica'),Indicador=paste('Indicador',1:7),Periodo=c('2022-2023','2023-2024','2022-2024'))
x[,`:=`(classe_periodo_label='Inconclusivo',rotulo_celula='+2,5 p.p. [-1,2;5,4]\nn=25; q=0,240\nLB INC +2,3; q=0,280')]
x[,Indicador:=factor(Indicador)];x[,Periodo:=factor(Periodo)];antes<-copy(x)
p<-file.path(dir,'figuras','evidencia_estatistica_teste.png')
e$monitora_v305_figura_evidencia(x,'Evidência temporal — teste',p,c(Inconclusivo='#BDBDBD'),function(n,d)d)
a<-fread(file.path(dir,'layout_evidencias.csv'));stopifnot(identical(x,antes),nrow(a)==1L,a$resultados==42L,a$largura_pol<=6.65,a$altura_pol<=8.15,a$texto_largura_mm<a$largura_celula_mm,a$texto_altura_mm<a$altura_celula_mm,length(list.files(file.path(dir,'figuras')))==1)
stopifnot(all(dim(png::readPNG(p))[1:2]>1000L))
e$monitora_v305_figura_evidencia(x,'Outro tema',file.path(dir,'figuras','outro.png'),c(Inconclusivo='#BDBDBD'),function(n,d)d)
stopifnot(nrow(fread(file.path(dir,'layout_evidencias.csv')))==2L)
d<-xml2::read_html('<html><head></head><body><table><thead><tr><th>Ano</th><th>Referência</th></tr></thead><tbody><tr><td>2026</td><td>Linha de base (2019;2021;2022;2023;2024;2025)</td></tr></tbody></table></body></html>')
e$monitora_relatorios_analiticos_html_colunas(d)
t<-xml2::xml_find_first(d,'.//table');stopifnot(grepl('monitora-tabela-curta',xml2::xml_attr(t,'class')),grepl('\u200B',xml2::xml_text(t),fixed=TRUE),!grepl('landscape',as.character(d),fixed=TRUE))
unlink(dir,recursive=TRUE);cat('PASS: figura única com todas as células, medidas reais, dados intactos e tabela curta em retrato.\n')
