# Somente helpers de inventário; não carrega o build nem regenera mapas.
source('tools/v305/siglas_figuras.R')
local({
  inventario<-monitora_v305_inventariar_siglas_mapa
  vazio<-inventario('sem siglas')
  stopifnot(identical(names(vazio),c('sigla','significado','contexto')),nrow(vazio)==0L)
  sirgas<-inventario('SIRGAS2000 / UTM zona 22S (EPSG:31982) MSI L2A RGB B04-B03-B02 PEC/PEC-PCD',c('GO','PA','GO'),'MMA')
  stopifnot(all(c('SIRGAS2000','UTM','EPSG','MSI','L2A','RGB','B04','B03','B02','PEC','PEC-PCD','MMA','GO (localizador)','PA (localizador)') %in% sirgas$sigla))
  stopifnot(!any(c('WGS84','WGS 84','PA','SP (localizador)','AAF-ICMBio') %in% sirgas$sigla),sum(sirgas$sigla=='GO (localizador)')==1L)
  stopifnot(sirgas$significado[sirgas$sigla=='PA (localizador)']=='Pará')
  # Siglas de estado nunca são deduzidas de palavras ou códigos no quadro.
  stopifnot(nrow(inventario('PA GO SP xRGB RGBx AAMSI'))==0L)
  wgs<-inventario('WGS 84 / UTM; AAF-ICMBio; UA',character())
  stopifnot(all(c('WGS 84','UTM','AAF-ICMBio','ICMBio','UA') %in% wgs$sigla),!any(c('SIRGAS2000','MMA','UAs') %in% wgs$sigla))
  stopifnot('WGS84'%in%inventario('WGS84')$sigla)
  # Bytes opacos bastam: o helper não lê nem modifica pixels.
  raiz<-tempfile('v305_siglas_');dir.create(file.path(raiz,'figuras','setor'),recursive=TRUE)
  on.exit(unlink(raiz,recursive=TRUE),add=TRUE)
  a<-file.path(raiz,'figuras','mapa.png');b<-file.path(raiz,'figuras','setor','mapa.png')
  writeBin(as.raw(1:10),a);writeBin(as.raw(11:20),b)
  avulsa<-file.path(raiz,'avulsa.png');writeBin(as.raw(1:10),avulsa)
  monitora_v305_registrar_siglas_figura(avulsa,sirgas)
  stopifnot(nrow(monitora_v305_ler_siglas_figura(avulsa,raiz))==nrow(sirgas))
  antes<-tools::md5sum(c(a,b))
  monitora_v305_registrar_siglas_figura(a,sirgas)
  monitora_v305_registrar_siglas_figura(b,wgs)
  ler<-function(f)monitora_v305_ler_siglas_figura(f,raiz)
  stopifnot(nrow(ler('figuras/mapa.png'))==nrow(sirgas),nrow(ler(b))==nrow(wgs),nrow(ler('nao_existe.png'))==0L)
  csv<-file.path(raiz,'siglas_figuras.csv');bytes<-readBin(csv,'raw',n=file.info(csv)$size)
  monitora_v305_registrar_siglas_figura(a,sirgas)
  stopifnot(identical(bytes,readBin(csv,'raw',n=file.info(csv)$size)),identical(antes,tools::md5sum(c(a,b))))
  # Regenerar um mapa substitui seu inventário e mantém o outro, mesmo basename.
  monitora_v305_registrar_siglas_figura(a,vazio)
  stopifnot(nrow(ler(a))==0L,nrow(ler(b))==nrow(wgs))
  writeBin(as.raw(21:30),b)
  stopifnot(inherits(try(ler(b),silent=TRUE),'try-error'))
  cat('PASS: inventário contextual, referenciais, limites de tokens, estados e logos efetivamente emitidos.\n')
  cat('PASS: CSV por relatório, chaves relativas distintas, idempotência, substituição, pixels preservados e checksum obsoleto rejeitado.\n')
})
